config/urls.py
from django.contrib import admin
from django.urls import path, include
from matchat import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('matchat/', include('matchat.urls')),
    path('api_same_check/', include('api_same_check.urls')),
    path('api_paycheck/', include('api_paycheck.urls')),
    path('api_finish/', include('api_finish.urls')),
    path('predict/', include('image_classification.urls')),
    path('', views.main, name='main'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_classification/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'image_classification'
urlpatterns = [
    # two paths: with or without given image
    path('', views.index, name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matchat/urls.py
from django.urls import path
from matchat import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'matchat'

urlpatterns =[
   path('', views.main, name='main'),
   path('<int:product_id>/', views.detail, name='detail'),
   path('product/create/', views.product_create, name='product_create'),
   path('product/modify/<int:product_id>/', views.product_modify, name='product_modify'),
   path('product/delete/<int:product_id>/', views.product_delete, name='product_delete'),
   path('product/reserve/<int:product_id>/', views.product_reserve, name='product_reserve'),
   path('product/reserve_delete/<int:product_id>/', views.product_reserve_delete, name='product_reserve_delete'),
   path('product/my/', views.product_my, name='my'),
   path('product/my/<int:product_id>/', views.my_detail, name='my_detail'),
   path('pay/<int:product_id>/', views.pay, name='pay'),
   path('pay/approval/', views.approval, name='approval'),
   path('pay/cancel/', views.cancel, name='cancel'),
   path('pay/fail/', views.fail, name='fail'),
]

matchat/models.py
from django.db import models
from django.contrib.auth.models import User


def directory_path(instance, filename):
    return f'{instance.product.author}/{instance.product.name}/{filename}'

class Product(models.Model):
    name = models.CharField(max_length=100) # 상품명
    use_period = models.CharField(max_length=50) # 사용기간
    price = models.CharField(max_length=10) #가격
    content = models.TextField(null=True)
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    reservation = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservation', null=True, blank=True)
    state = models.CharField(max_length=1, default='0')
    key = models.IntegerField(null=True)  # 우리가 랜덤으로 부여
    place = models.CharField(max_length=10, default='이대역') # 지점
    kiosk_photo = models.CharField(max_length=2090, null=True, blank=True) #kiosk 사진의 url 저장
    kiosk_result = models.CharField(max_length=100, default='none')
    web_result = models.CharField(max_length=100, default='none')

    def __str__(self):
        return self.name

class Photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to=directory_path, blank=True, null=True)

class Credit_Info(models.Model):
    card_com= models.CharField(max_length=20)
    card_num1=models.CharField(max_length=20)
    card_num2=models.CharField(max_length=20)
    card_num3=models.CharField(max_length=20)
    card_num4=models.CharField(max_length=20)
    cvc_num=models.CharField(max_length=20)
    dead_year=models.CharField(max_length=20)
    dead_month=models.CharField(max_length=20)

matchat/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'use_period', 'price', 'content', 'place']
        labels = {
            'name': '상품명',
            'use_period': '사용기간',
            'price': '가격',
            'content': '설명',
            'place': '지점',
        }

matchat/views.py
import os
import urllib

from decouple import config

from django.contrib import messages
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404

from chatbot.dialogflowApi import update_intent, batch_update_intents
from chatbot.dialogflow_ID import intent_id
from .models import Product, Photo
from .forms import ProductForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from random import randint


from django.http import HttpResponse, JsonResponse
from django.views import templates
import requests
import json


def main(request):
    product_list = Product.objects.order_by('-create_date')
    context = {'product_list': product_list}
    return render(request, 'main.html', context)


def index(request):
    # 상품 목록
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'low':
        product_list = Product.objects.order_by('price')
    elif so == 'high':
        product_list = Product.objects.order_by('-price')
    elif so == 'old':
        product_list = Product.objects.order_by('create_date')
    else:
        product_list = Product.objects.order_by('-create_date')

    # 검색
    if kw:
        product_list = product_list.filter(
            Q(name__icontains=kw) |  # 상품명 검색
            Q(content__icontains=kw) |  # 설명 검색
            Q(author__username__icontains=kw)  # 판매자 검색
        ).distinct()
    paginator = Paginator(product_list, 10)
    page_obj = paginator.get_page(page)

    context = {'product_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'matchat/product_list.html', context)


def detail(request, product_id):
    # 상세 페이지
    product = get_object_or_404(Product, pk=product_id)
    response = [
        "상품 이름은 " + product.name + "입니다.",
        "상품 가격은 " + product.price + "원 입니다.",
        "수령할 위치는 " + product.place + "입니다.",
        "상세 설명:" + product.content,
        product.kiosk_photo,
        "사용 기간은 " + product.use_period + "입니다.",
        product.name,
        "판매자 이름은 " + str(product.author) + "입니다."
    ]

    name = list(intent_id.keys())
    # update_intent(name[0], response[0], 0)
    # for i in range(len(response)):
    #     if i == 4:
    #         update_intent(name[i], response[i], 1)
    #     else:
    #         update_intent(name[i], response[i], 0)

    batch_update_intents(list(intent_id.keys()), response)

    context = {'product': product}
    return render(request, 'matchat/product_detail.html', context)


def my_detail(request, product_id):
    # 상세 페이지
    # product = get_object_or_404(Product, pk=product_id)
    product = get_object_or_404(Product, pk=product_id)
    context = {'product': product}
    return render(request, 'matchat/my_product_detail.html', context)


def detect_photo(img, product):
    #img_str = str(img)
    TEST_IMG = "http://ec2-3-39-141-76.ap-northeast-2.compute.amazonaws.com/media/admin/test444/22.jpg" # 기존 서버에 있는 이미지
    res = requests.post("http://ec2-15-164-129-198.ap-northeast-2.compute.amazonaws.com:5000/predict", files={"url": TEST_IMG}).json()
    return res[0]['name']


@login_required(login_url='account:login')
def product_create(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.create_date = timezone.now()
            product.author = request.user
            product.key = randint(10000, 99999)
            product.save()
            for img in request.FILES.getlist('photo'):
                photos = Photo()
                photos.product = product
                photos.photo = img
                photos.save()
                product.web_result = detect_photo(img, product)
                product.save()
            return redirect('matchat:main')
    else:
        form = ProductForm()
    context = {'form': form}
    return render(request, 'matchat/product_form.html', context)


@login_required(login_url='account:login')
def product_modify(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('matchat:detail', product_id=product.id)

    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.save()
            product.photo_set.all().delete()
            for img in request.FILES.getlist('photo'):
                photos = Photo()
                photos.product = product
                photos.photo = img
                photos.save()
            return redirect('matchat:detail', product_id=product.id)
    else:
        form = ProductForm(instance=product)
    context = {'form': form}
    return render(request, 'matchat/product_form.html', context)


@login_required(login_url='account:login')
def product_delete(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('account:detail', product_id=product.id)
    product.delete()
    return redirect('matchat:main')


@login_required(login_url='account:login')
def product_reserve(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.reservation = request.user
    product.state = '2'  # 결제를 하면 상태 2(결제완료) 로 변경
    product.save()
    return redirect('matchat:detail', product_id=product.id)


# 예약 취소를 위한 함수 -> 예약 기능이 사라져서 사용 X
@login_required(login_url='account:login')
def product_reserve_delete(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.reservation = None
    product.state = '1'  # 취소를 하면 1(등록완료) 로 변경
    product.save()
    return redirect('matchat:detail', product_id=product.id)


def product_my(request):
    product_list = Product.objects.order_by('-create_date')
    context = {'product_list': product_list}
    return render(request, 'matchat/my_product_list.html', context)


@login_required(login_url='account:login')
def pay(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.state='2'
    product.reservation = request.user # reservation = 구매자, 구매자는 detail 페이지에서 인증번호 봐야하므로 reservation 업데이트
    product.save()
    if request.method == "POST":
        URL = 'https://kapi.kakao.com/v1/payment/ready'
        headers = {
            "Authorization": "KakaoAK " + config('ADMIN_KEY'),  # 변경불가
            "Content-type": "application/x-www-form-urlencoded;charset=utf-8",  # 변경불가
        }
        params = {
            "cid": "TC0ONETIME",  # 테스트용 코드
            "partner_order_id": '1',  # 주문번호
            "partner_user_id": request.user.username,  # 유저 아이디
            "item_name": product.key,  # 구매 물품 이름
            "quantity": "1",  # 구매 물품 수량
            "total_amount": product.price,  # 구매 물품 가격
            "tax_free_amount": '0',  # 구매 물품 비과세
            "approval_url": "http://ec2-3-39-94-66.ap-northeast-2.compute.amazonaws.com/matchat/pay/approval",
            "cancel_url": "http://ec2-3-39-94-66.ap-northeast-2.compute.amazonaws.com/matchat/pay/cancel",
            "fail_url": "http://ec2-3-39-94-66.ap-northeast-2.compute.amazonaws.com/matchat/pay/fail",
        }
        res = requests.post(URL, headers=headers, params=params)
        request.session['tid'] = res.json()['tid']  # 결제 승인시 사용할 tid를 세션에 저장
        next_url = res.json()['next_redirect_pc_url']  # 결제 페이지로 넘어갈 url을 저장
        return redirect(next_url)
    return render(request, 'matchat/pay.html')


def approval(request):
    URL = 'https://kapi.kakao.com/v1/payment/approve'
    headers = {
        "Authorization": "KakaoAK " + config('ADMIN_KEY'),
        "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
    }
    params = {
        "cid": "TC0ONETIME",  # 테스트용 코드
        "tid": request.session['tid'],  # 결제 요청시 세션에 저장한 tid
        "partner_order_id": '1',      # 주문번호
        "partner_user_id": request.user.username,    # 유저 아이디
        "pg_token": request.GET.get("pg_token"),  # 쿼리 스트링으로 받은 pg토큰
    }
    res = requests.post(URL, headers=headers, params=params)
    amount = res.json()['amount']['total']
    res = res.json()
    context = {
        'res': res,
        'amount': amount,
    }
    return render(request, 'matchat/approval.html', context)


def cancel(request):
    return render(request, 'matchat/cancel.html')


def fail(request):
    return render(request, 'matchat/fail.html')

templates/matchat/approval.html
{% extends 'base.html' %}
{% block content %}
  <div class="mt-5 pt-5 row justify-content-center">
    <h2 class="text-center my-5 col-12">결제가 완료되었습니다!</h2>
    <div class="col-4 p-5 bg-light">
      <div>
        <div class="my-3 row"><div class="h5 col-6">인증번호</div><div class="h6 col-6 text-right">{{ res.item_name }}</div></div>
      </div>
    </div>
  </div>
    <div class="mt-5 pt-3 text-center">
        <a href="{% url 'main' %}" class="btn btn-warning">메인으로 돌아가기</a><br>
    </div>
  </div>

{% endblock %}

templates/matchat/cancel.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5 pt-3 row justify-content-center">
  <h2 class="text-center my-5 col-12">결제가 취소되었습니다!</h2>
      <div class="col-12 text-center">
        <a href="{% url 'main' %}" class="btn btn-warning">메인으로 돌아가기</a>
      </div>
  </div>

{% endblock %}

templates/matchat/fail.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5 pt-5 row justify-content-center">
  <h2 class="text-center my-5 col-12">결제 실패</h2>
      <div class="col-12 text-center">
        <a href="{% url 'main' %}" class="btn btn-warning">메인으로 돌아가기</a>
      </div>
  </div>

{% endblock %}

templates/matchat/my_product_detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container my-3">
<br>
    <h2 class="border-bottom py-2"> MY {{ product.name }}
    </h2>
    <div class="badge badge-dark p-2">
        가격 : {{ product.price }} (원)
    </div>
    <div class="badge badge-dark p-2">
        사용기간 : {{ product.use_period }}
    </div>
    <div class="badge badge-dark p-2">
        지점 : {{ product.place }}
    </div>
    <div class="badge badge-secondary p-2">
        판매자 : {{ product.author }}
    </div>
    <div class="badge badge-secondary p-2">
        사전등록일 : {{ product.create_date }}
    </div>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
            {{ product.content }}
            {% for img in product.photo_set.all%}
                    <img src="{{ img.photo.url }}" width="75%">
            {% endfor %}
            </div>
            <div class="d-flex justify-content-end">
                {% if request.user == product.author or request.user == product.reservation%}
                <div class="badge badge-danger p-2">
                    인증 번호 : {{ product.key }}
                </div>
                {% endif %}
            </div>
        </div>
         {% if request.user == product.author %}
            <div>
                <a href="{% url 'matchat:product_modify' product.id  %}"
                   class="btn btn-sm btn-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-danger"
                   data-uri="{% url 'matchat:product_delete' product.id  %}">삭제</a>
            </div>
            {% endif %}
    </div>
<a href="{% url 'matchat:my' %}" class="btn btn-primary">MY 목록</a>

{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/matchat/my_product_list.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
        </div>
    <table class="table table-hover">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>상품</th>
            <th>상품명</th>
            <th>가격 (원)</th>
            <th>상태</th>
            <th>지점</th>
            <th>판매자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        <br>
        <h3>{{request.user}}의 마이페이지</h3>
        <br>
        <br>
        <br>
        {% if product_list %}
        {% for product in product_list %}
        {% if request.user == product.author %}
        <tr class="text-center">
            <td>{{ forloop.counter }}</td>
            <td>
            {% for img in product.photo_set.all.filter%}
                {% if forloop.first %}
                    <img src="{{ img.photo.url }}" height="75">
                {% endif %}
            {% endfor %}
            </td>
            <td>
                <a href="{% url 'matchat:my_detail' product.id %}">{{ product.name }}</a>
            </td>
            <td>{{ product.price }}</td>

            {% if product.state == '0' %}
                <td><font color=grey>사전등록</font></td>
            {% elif product.state == '1' %}
                <td>등록완료</td>
            {% elif product.state == '2' %}
                <td><font color=red>결제완료</font></td>
            {% else %}
                <td><font color=grey>판매완료<font></td>
            {% endif %}
            <td>{{ product.place }}</td>
            <td>{{ product.author.username }}</td>
            <td>{{ product.create_date }}</td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">상품이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
<a href = "{% url 'matchat:product_create'%}" class="btn btn-primary">사전등록</a>
{% endblock %}

templates/matchat/pay.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
  <div class="row mt-5">
    <h1 class="col-12 text-center my-5">KAKAO PAY</h1>
    <form method="post" class="col-12 text-center">
      {% csrf_token %}
      <button class="btn btn-warning">카카오페이로 결제하기</button>
    </form>
  </div>
{% endblock %}

templates/matchat/product_detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container my-3">
<br>
    <h2 class="border-bottom py-2">{{ product.name }}
    </h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
            {% for img in product.photo_set.all%}
                    <img src="{{ img.photo.url }}" width="75%">
            {% endfor %}
            </div>
            <div class="d-flex justify-content-end">
                {% if request.user == product.author or request.user == product.reservation%}
                <div class="badge badge-danger p-2">
                    인증 번호 : {{ product.key }}
                </div>
                {% endif %}
            </div>
        </div>
         {% if request.user == product.author %}
            <div>
                <a href="{% url 'matchat:product_modify' product.id  %}"
                   class="btn btn-sm btn-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-danger"
                   data-uri="{% url 'matchat:product_delete' product.id  %}">삭제</a>
            </div>
            {% endif %}
    </div>
<a href="{% url 'main' %}" class="btn btn-primary">메인</a>
{% if request.user != product.author %}
    {% if product.state == '0' %}
        <a href="" class="btn btn-danger">결제불가</a>
    {% elif product.state == '1' %}
        <a href="{% url 'matchat:pay' product.id %}" class="btn btn-outline-info">결제</a>
    {% elif product.state == '2' %}
        <a href="" class="btn btn-danger">결제완료</a>
    {% else %}
        <a href="" class="btn btn-danger">판매완료</a>
    {% endif %}
{% endif %}

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>

        <style>
          df-messenger {
           --df-messenger-button-titlebar-color: #20c997;
           --df-messenger-send-icon: #20c997;
          }
        </style>
        <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
        <df-messenger
          intent="WELCOME"
          chat-title="matchat"
          agent-id="34c4542d-8b06-4eb4-96f7-65b354cedf35"
          language-code="ko"
        ></df-messenger>

{% endblock %}

templates/matchat/product_form.html
{% extends 'base.html' %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <h2 class="my-3 border-bottom pb-2">사전 등록</h2>
    <form method="post" action="" enctype="multipart/form-data" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="photo">상품사진</label>
            <input type="file"  class="form-control" name="photo" id="photo"
                   value="{{ form.photo.value|default_if_none:'' }}" multiple>
        </div>
        <div class="form-group">
            <label for="name">상품명</label>
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="price">판매가격</label>
            <input type="text" class="form-control" name="price" id="price"
                   value="{{ form.price.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="use_period">사용기간</label>
            <input type="text" class="form-control" name="use_period" id="use_period"
                   value="{{ form.use_period.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">설명</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <div class="form-group">
            <label for="place">지점</label> <br>
            <label><input type="radio" name="place" id="place" value="이대역"> 이대역 </label><br>
            <label><input type="radio" name="place" id="place" value="방배역"> 방배역 </label><br>
            <label><input type="radio" name="place" id="place" value="혜화역"> 혜화역 </label><br>
            <label><input type="radio" name="place" id="place" value="매봉역"> 매봉역 </label><br>
        </div>
        <button type="submit" class="btn btn-primary">등록</button>
    </form>
</div>

{% endblock %}

templates/matchat/product_list.html
{% extends 'base.html' %}
{% load matchat_filter %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="old" {% if so == 'old' %}selected{% endif %}>오래된순</option>
                <option value="low" {% if so == 'low' %}selected{% endif %}>가격낮은순</option>
                <option value="high" {% if so == 'high' %}selected{% endif %}>가격높은순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th>상품</th>
            <th>상품명</th>
            <th>가격 (원)</th>
            <th>상태</th>
            <th>지점</th>
            <th>판매자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if product_list %}
        {% for product in product_list %}
        <!--상태 1은 등록완료된 상품, 상태 2는 결제완료된 상품. 두 가지 상태만 띄우기-->
        {% if product.state == '1' or product.state == '2' %}
        <tr class="text-center">
            <td>{{product_list.paginator.count|sub:product_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
            {% for img in product.photo_set.all.filter%}
                {% if forloop.first %}
                    <img src="{{ img.photo.url }}" height="75">
                {% endif %}
            {% endfor %}
            </td>

            <td>
                <a href="{% url 'matchat:detail' product.id %}">{{ product.name }}</a>
            </td>
            <td>{{ product.price }}</td>

            {% if product.state == '2' %}
                <td><font color=red>결제완료</font></td>
            {% else %}
                <td>등록완료</td>
            {% endif %}
            <td>{{ product.place }}</td>
            <td>{{ product.author.username }}</td>
            <td>{{ product.create_date }}</td>

        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">상품이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if product_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ product_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in product_list.paginator.page_range %}
        {% if page_number >= product_list.number|add:-5 and page_number <= product_list.number|add:5 %}
            {% if page_number == product_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if product_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ product_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href = "{% url 'matchat:product_create'%}" class="btn btn-primary">사전등록</a>
</div>
<form id="searchForm" method="get" action="{% url 'matchat:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}

{% endblock %}