account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from account import views

app_name = 'account'

urlpatterns =[
    path('login/', auth_views.LoginView.as_view(template_name = 'account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from matchat import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('matchat/', include('matchat.urls')),
    path('api_same_check/', include('api_same_check.urls')),
    path('api_paycheck/', include('api_paycheck.urls')),
    path('api_finish/', include('api_finish.urls')),
    path('predict/', include('image_classification.urls')),
    path('', views.main, name='main'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matchat/urls.py
from django.urls import path
from matchat import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'matchat'

urlpatterns =[
   path('', views.main, name='main'),
   path('<int:product_id>/', views.detail, name='detail'),
   path('product/create/', views.product_create, name='product_create'),
   path('product/modify/<int:product_id>/', views.product_modify, name='product_modify'),
   path('product/delete/<int:product_id>/', views.product_delete, name='product_delete'),
   path('product/reserve/<int:product_id>/', views.product_reserve, name='product_reserve'),
   path('product/reserve_delete/<int:product_id>/', views.product_reserve_delete, name='product_reserve_delete'),
   path('product/my/', views.product_my, name='my'),
   path('product/my/<int:product_id>/', views.my_detail, name='my_detail'),
   path('pay/<int:product_id>/', views.pay, name='pay'),
   path('pay/approval/', views.approval, name='approval'),
   path('pay/cancel/', views.cancel, name='cancel'),
   path('pay/fail/', views.fail, name='fail'),
]

matchat/models.py
from django.db import models
from django.contrib.auth.models import User


def directory_path(instance, filename):
    return f'{instance.product.author}/{instance.product.name}/{filename}'

class Product(models.Model):
    name = models.CharField(max_length=100) # 상품명
    use_period = models.CharField(max_length=50) # 사용기간
    price = models.CharField(max_length=10) #가격
    content = models.TextField(null=True)
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    reservation = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservation', null=True, blank=True)
    state = models.CharField(max_length=1, default='0')
    key = models.IntegerField(null=True)  # 우리가 랜덤으로 부여
    place = models.CharField(max_length=10, default='이대역') # 지점
    kiosk_photo = models.CharField(max_length=2090, null=True, blank=True) #kiosk 사진의 url 저장
    kiosk_result = models.CharField(max_length=100, default='none')
    web_result = models.CharField(max_length=100, default='none')

    def __str__(self):
        return self.name

class Photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to=directory_path, blank=True, null=True)

class Credit_Info(models.Model):
    card_com= models.CharField(max_length=20)
    card_num1=models.CharField(max_length=20)
    card_num2=models.CharField(max_length=20)
    card_num3=models.CharField(max_length=20)
    card_num4=models.CharField(max_length=20)
    cvc_num=models.CharField(max_length=20)
    dead_year=models.CharField(max_length=20)
    dead_month=models.CharField(max_length=20)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko-kr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

        <title>MATCHAT</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href=" {% static 'assets/logo.PNG' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
<!--
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>MATCHAT</title>
</head>
<body>
-->
{%include "navbar.html"%}
{% block content %}
{% endblock %}
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" style="border-radius: 20%" src="{% static 'assets/logo.PNG' %}" alt="..." />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">MATCHAT</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">편리하고 신뢰할 수 있는 중고거래 플랫폼</p>
            </div>
        </header>
        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">상품목록</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                <!-- Portfolio Item -->

                {% if product_list %}
                {% for product in product_list %}
                    {% if product.state == '1' or product.state == '2' %}
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#{{product.name}}">
                            <a href = "{% url 'matchat:detail' product.id %}">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            </a>
                            {% for img in product.photo_set.all.filter%}
                                     {% if forloop.first %}
                                           <img src="{{ img.photo.url }}" height="400">
                                     {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                       {% endif %}
                    {% endfor %}
                    {% endif %}
                </div>

            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">이용방법</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-4 ms-auto">
                    <h3 align="center">판매</h3>
                    <p class="lead" align="center">
                    [사전등록] 을 통해 상품 등록하기<br>
                    해당 지점에 가서 상품 [등록완료] 하기 <br>
                    등록이 완료되면 상품을 [락커] 에 넣기<br>
                    구매자가 결제를 하면 [자동입금] <br>
                    </p></div>
                    <div class="col-lg-4 me-auto">
                    <h3 align="center">구매</h3>
                    <p class="lead" align="center">
                    원하는 상품을 [클릭] 하기 <br>
                    [결제] 버튼을 통해 결제하기<br>
                    해당 지점 [락커] 에서 물건을 수령하기<br>
                    상품 문의는 [챗봇] 이용하기<br>
                    </p></div>
                </div>
                <!-- About Section Button-->
                <div class="text-center mt-4">
                    <a class="btn btn-xl btn-outline-light" href="{% url 'matchat:product_create' %}">
                        <i class="fas fa-download me-2"></i>
                        사전등록
                    </a>
                </div>
            </div>
        </section>
        <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                {% if user.is_authenticated %}
                    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">로그아웃</h2>
                {% else %}
                    <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">로그인</h2>
                {% endif %}
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Contact Section Form-->
                <div class="text-center mt-4">
                   {% if user.is_authenticated %}
                       <a class="btn btn-primary btn-lg" href="{% url 'account:logout' %}">
                            로그아웃
                        </a>
                   {% else %}
                        <a class="btn btn-primary btn-lg" href="{% url 'account:login' %}">
                            로그인
                        </a>
                   {% endif %}
               </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            이대역 1호점
                            <br />
                            방배역 2호점
                            <br />
                            혜화역 3호점
                            <br />
                            매봉역 4호점
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Contact Us</h4>
                        <p class="lead mb-0">
                        rkdfc93@gmail.com<br>
                        soyun9902@ewhain.net<br>
                        guswn1112017@naver.com<br>
                        johayeon@ewhain.net<br>
                        </p>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About i4</h4>
                        <p class="lead mb-0">
                            We are 설유진, 원소윤, 이현주, 조하연<br>
                            from Capstone Design Project 31 Team I4.<br>
                            Department of Computer Science and Engineering, Ewha Womans University.<br>
                            From September 2021 to June 2022.
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; MATCHAT 2022 by i4</small></div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
{% endblock %}

{% block script %}
<script>

</script>
{% endblock %}

templates/navbar.html
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main' %}" >MATCHAT</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" >
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account:logout' %}">로그아웃</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'matchat:my' %}">MY</a></li>
                    {% else %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account:login' %}">로그인</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account:signup' %}">회원가입</a></li>
                    {% endif %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'matchat:product_create' %}">사전등록</a></li>
                    </ul>
                </div>
            </div>
        </nav>